// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmcyqhjrdfhfdzpupryj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtY3lxaGpyZGZoZmR6cHVwcnlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODUzNDksImV4cCI6MjA2NjI2MTM0OX0.bTzqo4k60Zg6vDdF8-lZiNQkaCIWBtHRYNLPGX6d5lE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);